#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  rightJumper,    sensorDigitalIn)
#pragma config(Sensor, dgtl2,  nocrashJumper,  sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           Right_Drive,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Left_Elev,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Right_Elev,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Left_Toss,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Right_Toss,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Brush,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          Left_Drive,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)
int tosserspeed; //declare the variable for tosserspeed
bool motorFlag=false;

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
//
// Grand Blanc Middle School Vex Team 6838C Presents
//
// Charlie 2.0 in Nothing But Net
//
// Coming soon to a competition near you!
//
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Driver Control Task
//
// This task contains the controls to drive the robot in manual mode.
//
/////////////////////////////////////////////////////////////////////////////////////////

task drivercontrols()
{
//set variables


//Tank Drive - drive motors operating off main joystick
	if (vexRT[Btn5U] != 0) //When left top trigger isn't pressed
	{
		motor[Left_Drive] = (abs(vexRT[Ch3]) > 10) * vexRT[Ch3];// Need to calibrate joysticks
		motor[Right_Drive] = vexRT[Ch2];
	}
	else
	{
		motor[Left_Drive] = vexRT[Ch3] / 2;
		motor[Right_Drive] = vexRT[Ch2] / 2;
	}


	//Brush bar control
		if (vexRT[Btn8RXmtr2]==1)
	{
		motor[Brush]=127;
	}
	else if (vexRT[Btn8RXmtr2]==0)
	{
		motor[Brush]=0;
	}//end brush control

	//Elevator motors up - operating off 2ndary controller, button 5U
	if (vexRT[Btn5UXmtr2]==1)
	{
		motor[Left_Elev]=-127;
		motor[Right_Elev]=-127;
	}
	else if (vexRT[Btn5UXmtr2]==0)
	{
		motor[Left_Elev]=0;
		motor[Right_Elev]=0;
	}


	//Elevator motors down - operating off 2ndary controller, button 5D
	if (vexRT[Btn5DXmtr2]==1)
	{
		motor[Left_Elev]=127;
		motor[Right_Elev]=127;
	}


	// Tossing motors on - operating off 2ndary controller, button 6U
	if (vexRT[Btn6UXmtr2]==1)
	{
		motorFlag=true;
	}

	if (motorFlag)
	{
		motor[Left_Toss]=tosserspeed;
		motor[Right_Toss]=tosserspeed;
	}

	// Tossing motors off - operating off 2ndary controller, button 6D
	if (vexRT[Btn6DXmtr2]==1)
	{
		motorFlag=false;
		motor[Left_Toss]=0;
		motor[Right_Toss]=0;
	}

	//Tosser Speed adjustment use buttons 8U and 8D to increase and decrease tosser speeds
	if((vexRT[Btn8UXmtr2]==1)&&(vexRT[Btn8DXmtr2]==0))//tosserspeed +10
	{
		tosserspeed = tosserspeed + 10;
	}
	else 	if((vexRT[Btn8UXmtr2]==0)&&(vexRT[Btn8DXmtr2]==1))//tosserspeed - 10
	{
		tosserspeed = tosserspeed - 10;
	}

	//Auto Shoot Balls - Shoots 3 Balls in a row once loaded and Button 8U pressed on 1st Controller
	if (vexRT[Btn8U]==1)
	{
		motor[Left_Elev]=-28;//run the elevators at 1/2 speed so we can auto feed and shoot balls
		motor[Right_Elev]=-45;
	}

}//end task drivercontrols

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Encoder Reset
//
// This task contains the code to reset the encoders back to zero.
//
/////////////////////////////////////////////////////////////////////////////////////////

void resetencoders()
{
	nMotorEncoder[Right_Drive] = 0;
	nMotorEncoder[Left_Drive] = 0;
}//end task resetencoders


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Drive Motor Control
//
// This task contains the code to control the drive motors.
//
/////////////////////////////////////////////////////////////////////////////////////////

void drivemotors(int V1, int V2)
{
	motor[Right_Drive] = V1;
	motor[Left_Drive] = V2;
}//end drive motor control

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Tosser Motor Control
//
// This task contains the code to control the tosser motors.
//
/////////////////////////////////////////////////////////////////////////////////////////

void tossers(int V1, int V2)
{
	motor[Right_Toss] = V1;
	motor[Left_Toss] = V2;
}//end tosser motor control

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Elevator Motor Control
//
// This task contains the code to control the elevator motors.
//
/////////////////////////////////////////////////////////////////////////////////////////

void elevators(int V1, int V2)
{
	motor[Left_Elev] = V1;
	motor[Right_Elev] = V2;
}//end elevators
/*

//////////////////////////////////////////////////////////////////////////////////////
//Display Battery Voltage
//ROBOTC on VEX 2.0 Cortex
//This program uses the Display functions of ROBOTC on the VEX 2.0 Cortex platform.
//It will display the value of the main battery on line 0 and backup battery on line 1.
//////////////////////////////////////////////////////////////////////////////////////
ROBOT CONFIGURATION
MOTORS &amp; SENSORS:
[I/O Port]                    [Name]                            [Type]                                [Description
UART Port 2                    none                             VEX LCD                                VEX LCD Screen

*/
void batterydisplay()
{
	bLCDBacklight = true;                 // Turn on LCD Backlight
	string mainBattery, backupBattery;

	//while(true)                           // An infinite loop to keep the program running until you terminate it
	// {
	clearLCDLine(0);                      // Clear line 1 (0) of the LCD
	clearLCDLine(1);                      // Clear line 2 (1) of the LCD

	//Display the Primary Robot battery voltage
	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	//Display the Backup battery voltage
	displayLCDString(1, 0, "Backup: ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
	displayNextLCDString(backupBattery);

	//Short delay for the LCD refresh rate
	wait1Msec(100);
	//}//end while loop
}//end void batterydisplay




/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

	/////////////////////////////////////////////////////////////////////////
	// starting in right red box
	////////////////////////////////////////////////////////////////////////

	clearTimer(T1);
	tossers(127,127); //turn the tosser motors on.
	while(time1[T1] <= 2250)
	{
	//	drivemotors(127,127); // drive forwards towards net
	}
	drivemotors(0,0); // stop the robot
	wait10Msec(1); // may remove this to turn on tossers and save time

	//tossers(127,127); //turn the tosser motors on.
	//wait10Msec(200); //give the tosser motors time to spin up.

	elevators(-117,-117); //shoot 1st ball.
	wait10Msec(5);
	elevators(0,0); //stop the elevators
	wait10Msec(125); //give the tosser motors time to spin up.

	elevators(-117,-117); //shoot 2nd ball.
	wait10Msec(50);
	elevators(0,0); //stop the elevators
	wait10Msec(125);//give the tosser motors time to spin up.

	elevators(-117,-117); //shoot 3rd ball.
	wait10Msec(55);
	elevators(0,0); //stop the elevators
	wait10Msec(125);

	elevators(-117,-117); //shoot 4th ball.
	wait10Msec(95);

	//elevators(0,0); //stop the elevators
	//tossers(0,0); //turn off tosser motors


} //end task autonomous

//}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	tosserspeed = 127; //set tosserspeed to max
	while(true)                     // infinite loop:
	{
		batterydisplay();


		startTask(drivercontrols);

		if(vexRT[Btn7U]==1)
		{



		}//end if loop
	}//end while loop
}//end task usercontrol
